### ISSUE TITLE
about the Bézier curve

### ISSUE THREAD

**Issue by THEONE10211024** [codesoup/android-cubic-bezier-interpolator#1]
is it a quartic Bézier curve? Can you tell me how to implement it. Thank you!

**Comment by marijnvdwerf** [comment]
I recommend using https://developer.android.com/reference/android/support/v4/view/animation/PathInterpolatorCompat.html instead. It probably has better performance, as Google is behind it.

**Comment by THEONE10211024** [comment]
I see, thank you very much!
